### ISSUE TITLE
issue with `asv publish` when main branch is not called `master`

### ISSUE THREAD

**Issue by zacharyburnett** [airspeed-velocity/asv#1236]
when running `asv publish`  or `asv gh-pages`, and the main branch is not called `master` (in this case `main`), the following error occurs:
```
[ 11.11%] · Loading machine info
[ 22.22%] · Getting params, commits, tags and branches
[ 22.22%] ·· Fetching recent changes.
[ 22.22%] ·· Error running /usr/bin/git rev-list --first-parent master (exit status 128)
             STDOUT -------->
             
             STDERR -------->
             fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
             Use '--' to separate paths from revisions, like this:
             'git <command> [<revision>...] -- [<file>...]'

Traceback (most recent call last):
  File "/home/zburnett/mambaforge/envs/bench/bin/asv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
             ^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/commands/publish.py", line 80, in run_from_conf_args
    return cls.run(conf=conf, range_spec=args.range, pull=not args.no_pull)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/commands/publish.py", line 171, in run
    branches = dict(
               ^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/commands/publish.py", line 172, in <genexpr>
    (branch, repo.get_branch_commits(branch))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/plugins/git.py", line 177, in get_branch_commits
    return self.get_hashes_from_range(self.get_branch_name(branch))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/plugins/git.py", line 125, in get_hashes_from_range
    output = self._run_git(args, valid_return_codes=(0, 1), dots=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/plugins/git.py", line 74, in _run_git
    return util.check_output([self._git] + args, env=env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zburnett/mambaforge/envs/bench/lib/python3.11/site-packages/asv/util.py", line 754, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git rev-list --first-parent master' returned non-zero exit status 128
```

**Comment by Patataman** [comment]
I had the same problem. Try in your asv.conf.json adding the key

```
"branches": ["name of your branch"],
```
