### ISSUE TITLE
ENH: Support `pdm`, `poetry`

### ISSUE THREAD

**Issue by HaoZeke** [airspeed-velocity/asv#1241]
Essentially any tool which is globally installed needs to be symlinked into the directory at the moment. As an example consider:

```json
    "install_command": ["in-dir={env_dir} pdm install"],
    "build_command": [
        "pdm build",
    ],
```

Which fails with the uninspiring (given that `environment.yml` includes `pdm`):

```bash
·· Building b941a98d <main> for virtualenv-py3.11
Traceback (most recent call last):
  File "/home/rgoswami/mambaforge/envs/expasv/bin/asv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/main.py", line 29, in main
    result = args.func(args)
             ^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/commands/run.py", line 166, in run_from_conf_args
    return cls.run(
           ^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/commands/run.py", line 290, in run
    benchmarks = Benchmarks.discover(conf, repo, environments,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/benchmarks.py", line 133, in discover
    benchmarks = cls._disc_benchmarks(conf, repo, environments, commit_hash, check)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/benchmarks.py", line 186, in _disc_benchmarks
    env.install_project(conf, repo, commit_hash)
  File "/home/rgoswami/Git/Github/Python/asv/asv/environment.py", line 815, in install_project
    self._build_project(repo, commit_hash, build_dir)
  File "/home/rgoswami/Git/Github/Python/asv/asv/environment.py", line 874, in _build_project
    self._interpolate_and_run_commands(cmd, default_cwd=build_dir,
  File "/home/rgoswami/Git/Github/Python/asv/asv/environment.py", line 773, in _interpolate_and_run_commands
    self.run_executable(cmd[0], cmd[1:], timeout=self._install_timeout, cwd=cwd,
  File "/home/rgoswami/Git/Github/Python/asv/asv/environment.py", line 939, in run_executable
    exe = self.find_executable(executable)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/environment.py", line 899, in find_executable
    return util.which(executable, paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgoswami/Git/Github/Python/asv/asv/util.py", line 347, in which
    raise IOError("Could not find '{0}' in {1}".format(filename, loc_info))
OSError: Could not find 'pdm' in /home/rgoswami/Git/Github/Python/exp_asv/.asv/env/2bc11cad084fa5bfe9c66b8a2af28d97/bin
```

Note that symlinking the `pdm` executable into `bin` will work.

**Comment by HaoZeke** [comment]
More concrete reproducers:

```bash
pdm init
# ASV expects a DVC repo
git init
git add .
git commit -m "Whatever"
asv quickstart
# modify the asv.conf.json as above
asv run -vv
```

**Comment by HaoZeke** [comment]
This is a bit of a none issue as this can be fixed by adding the relevant tool to the `matrix` key in the `json` file, e.g.:

```json
    "matrix": {
        "req": {
            "pdm": [""],
        },
    },
```

Though this should be picked up automaticall perhaps.
