### ISSUE TITLE
BUG: AttributeError: 'Log' object has no attribute '_colorama'

### ISSUE THREAD

**Issue by rgommers** [airspeed-velocity/asv#1333]
Observed with the latest `asv` release when trying to run the numpy benchmarks in a clean Ubuntu env:
```
$ asv run --dry-run --show-stderr --python=same --quick
Couldn't load asv.plugins.mamba because
No module named 'mamba'
Couldn't load asv.plugins.virtualenv because
No module named 'packaging'
Traceback (most recent call last):
· No information stored about machine 'fv-az364-118'. I know about nothing.
  File "/opt/hostedtoolcache/Python/3.9.17/x64/bin/asv", line 8, in <module>
  
    sys.exit(main())

  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/main.py", line 29, in main
    result = args.func(args)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/commands/run.py", line 166, in run_from_conf_args
    return cls.run(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/commands/run.py", line 189, in run
    machine_params = Machine.load(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/machine.py", line 196, in load
    d.update(self.generate_machine_file(use_defaults=use_defaults))
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/asv/machine.py", line 157, in generate_machine_file
    if not sys.stdout.isatty() and not use_defaults and not log._colorama:
AttributeError: 'Log' object has no attribute '_colorama'
```

**Comment by rgommers** [comment]
This code in `asv_runner/console.py` seems to assume that all non-Windows envs are a TTY, or something like that:
```
        if sys.platform in {"win32", "cli"}:
            try:
                import colorama

                colorama.init()
                self._colorama = True
            except Exception as exc:
                print(f"On Windows, colorama is suggested, but got {exc}")
```
This code is broken in GitHub Actions. Installing `colorama` doesn't make a difference, because `_colorama` is simply not an attribute due to this try-except.

**Comment by rgommers** [comment]
A workaround in GitHub Actions jobs is:
```yaml
    - name: Run benchmarks
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      run: |
        asv run ...
```
