### ISSUE TITLE
starts gh-pages branch anew instead of updating which forbids fast-forwarding push

### ISSUE THREAD

**Issue by yarikoptic** [airspeed-velocity/asv#515]
according to the description of `gh-pages` command it should update the branch, not rewrite (which complicates pushing).  But it seems to just rewrite it:

```shell
$> git lg gh-pages
* 5ddbbf63 - (origin/gh-pages, gh-pages) Generated from sources (4 months ago) [Yaroslav Halchenko]

$> asv gh-pages       
[ 11.11%] · Loading machine info
[ 22.22%] · Getting params, commits, tags and branches
[ 33.33%] · Loading results.
[ 44.44%] · Detecting steps
[ 55.56%] · Generating graphs
[ 66.67%] · Generating output for SummaryGrid
[ 77.78%] · Generating output for SummaryList
[ 88.89%] · Generating output for Regressions.
[100.00%] · Writing index
[100.00%] · Updating gh-pages branch
[100.00%] · Pushing gh-pages branch
[100.00%] · Error running /usr/bin/git push origin gh-pages
            STDOUT -------->
            
            STDERR -------->
            To github.com:datalad/datalad
             ! [rejected]          gh-pages -> gh-pages (non-fast-forward)
            error: failed to push some refs to 'git@github.com:datalad/datalad'
            hint: Updates were rejected because a pushed branch tip is behind its remote
            hint: counterpart. Check out this branch and integrate the remote changes
            hint: (e.g. 'git pull ...') before pushing again.
            hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/github.py", line 36, in run_from_conf_args
    return cls.run(conf=conf, no_push=args.no_push)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/github.py", line 69, in run
    util.check_call([git, 'push', 'origin', 'gh-pages'])
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/util.py", line 282, in check_call
    cwd=cwd)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/util.py", line 512, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git push origin gh-pages' returned non-zero exit status 1

$> git lg gh-pages
* 65997455 - (gh-pages) Generated from sources (6 seconds ago) [Yaroslav Halchenko]

$> asv --version
asv 0.2

```
so as you can see gh-pages just became a new branch without any preceding commit

**Comment by yarikoptic** [comment]
ah -- probably I see the reason.  asv assumes that its "content" directory is also under the same repository, but in our case `.asv/` is git submodule (why to burden main project tree with all the benchmark log files number of which could be in thousands?):
```
[100.00%] · Running '/usr/bin/git fetch .asv/html'
[100.00%] · STDOUT -------->
            
            STDERR -------->
            warning: no common commits
            From .asv/html
             * branch              HEAD       -> FETCH_HEAD

[100.00%] · Running '/usr/bin/git branch -f gh-pages FETCH_HEAD'
[100.00%] · STDOUT -------->
            
            STDERR -------->
            

[100.00%] · Pushing gh-pages branch
```
so, imho fix should be:
1. fetching command for asv's tree should be done under that directory (so if it is submodule -- would still work)
2. check for gh-pages branch should be done under the main (benchmarked) repository directory... or some config setting should instruct -- of which (sub)directory/repository to assume having gh-pages branch

**Comment by pv** [comment]
I think the rewrite is intended behavior, to avoid cluttering up the git 
repository with html output.

**Comment by pv** [comment]
Sorry, I'm wrong --- clearly it doesn't rewrite.

**Comment by yarikoptic** [comment]
I think it would be a good feature to have though, but as an option and then add `-f` to the push ;)

**Comment by TomAugspurger** [comment]
What's the intended / desired behavior here? IIUC we want a new option `--rewrite`, so that there's only ever a single commit on the `gh-pages` branch? And if `--rewrite` is set, we should force-push to GH-pages. But rewriting should not be the default?

I'm looking to setup an automated runner/publisher for pandas (and other NUMFocus projects). Since pandas includes the benchmark suite inside the main git repo, we'd prefer to rewrite.

**Comment by pv** [comment]
I don't have strong opinion, but I guess both rewrite and non-rewrite 
could be offered. (I'm not dogfooding this myself, which is probably why 
it's broken.)
