### ISSUE TITLE
asv preview not loading graphs. Lots of 404s in the console

### ISSUE THREAD

**Issue by asmeurer** [airspeed-velocity/asv#537]
I am trying to use asv to visualize the performance difference between two commits. I ran the benchmarks fine (it is [these](https://github.com/sympy/sympy_benchmarks) benchmarks, except I changed the repo url to my local repo). 

But when I `asv publish` and `asv preview`, none of the graphs load. In the console, I have a lot of errors like

```
:8080/graphs/summary/cse.TimeCSE.time_cse.json?_=1501786104493 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/dsolve.TimeDsolve01.time_dsolve.json?_=1501786104494 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/integrate.TimeIntegration01.time_doit.json?_=1501786104495 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/lambdify.TimeLambdifyCreation.time_lambdify_create.json?_=1501786104497 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.peakmem_jacobian_wrt_functions.json?_=1501786104499 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/integrate.TimeIntegration01.time_doit_meijerg.json?_=1501786104496 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/lambdify.TimeLambdifyEvaluate.time_lambdify_evaluate.json?_=1501786104498 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.peakmem_jacobian_wrt_symbols.json?_=1501786104500 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_cse.json?_=1501786104503 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_count_ops.json?_=1501786104502 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.peakmem_subs.json?_=1501786104501 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_free_symbols.json?_=1501786104504 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_jacobian_wrt_functions.json?_=1501786104505 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_jacobian_wrt_symbols.json?_=1501786104506 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/logic.LogicSuite.time_dpll.json?_=1501786104509 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/logic.LogicSuite.time_dpll2.json?_=1501786104510 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_manual_jacobian_wrt_functions.json?_=1501786104507 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/large_exprs.TimeLargeExpressionOperations.time_subs.json?_=1501786104508 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/logic.LogicSuite.time_load_file.json?_=1501786104511 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixArithmetic.time_dense_multiply.json?_=1501786104515 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixOperations.time_det.json?_=1501786104516 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/physics.mechanics.kane.KanesMethodMassSpringDamper.time_kanesmethod_mass_spring_damper.json?_=1501786104512 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixOperations.time_det_berkowitz.json?_=1501786104518 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixArithmetic.time_dense_add.json?_=1501786104514 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/physics.mechanics.lagrange.LagrangesMethodMassSpringDamper.time_lagrangesmethod_mass_spring_damper.json?_=1501786104513 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixOperations.time_det_bareiss.json?_=1501786104517 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixOperations.time_rank.json?_=1501786104519 Failed to load resource: the server responded with a status of 404 (File not found)
:8080/graphs/summary/solve.TimeMatrixOperations.time_rref.json?_=1501786104520 Failed to load resource: the server responded with a status of 404 (File not found)
```

I've tried clearing the `html` directory and republishing and it doesn't help. 

This is with asv 0.2. I also tried using the git version, but that failed:

```
$PYTHONPATH=~/Documents/asv python -m asv publish
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/aaronmeurer/Documents/asv/asv/__init__.py", line 17, in <module>
    from ._version import __version__, __githash__, __release__
ImportError: No module named 'asv._version'
```

**Comment by pv** [comment]
The git version probably isn't properly installed if asv._version is
missing --- setup.py should create it.

**Comment by asmeurer** [comment]
Hmm, why do I have to run setup.py to "compile" asv? Isn't it pure Python?

**Comment by asmeurer** [comment]
Oh I see now that it isn't. I'm sure yall have a good reason for it not being so.

At the very least, it would be nice to get a better ImportError if build_ext hasn't been run.

**Comment by pv** [comment]
Well, that's how it works now. Also, it's not pure-python.

**Comment by pv** [comment]
Of course, there's no reason to require `_version.py` to be present, and the non-Python parts are optional. Pull requests making importing `_version.py` optional are accepted.

**Comment by asmeurer** [comment]
Usually one stores the version in the package and reads it from setup.py, not the other way around. 

If you want to include the git revision, I recommend using versioneer, which handles all this logic for you, and does it the "right" way.

**Comment by asmeurer** [comment]
Anyway, back to the original issue, I got the dev version working, and the bug still persists there.

**Comment by pv** [comment]
If you can upload the stuff (results etc) needed to run "asv preview"
etc. somewhere that can help debugging, that can be useful (don't have
time to look into it immediately though)

**Comment by asmeurer** [comment]
Let me know if [this](https://github.com/asmeurer/sympy_benchmarks/tree/test-results) is enough (I just did `git add -f results`). There is also `env` and `sympy` directories, but they are both huge.

**Comment by pv** [comment]
I think the reason why it doesn't generate any data points is because the benchmark results are not on the branch in asv.conf.json (at least for me, those commits don't exist in the repository --- maybe your situation is different?). The generated website only contains results for commits on the branches configured.

**Comment by asmeurer** [comment]
Thanks, that was the ticket. I am trying to use asv to just get an idea if a change that I want to make is slower or faster, so it isn't in master.

**Comment by pv** [comment]
The web ui has not really been done with that use case in mind, so it may be clumsy to use for that. With two commits, the step detection algorithms in the web ui will also not give you results since there's no statistics.

On command line `asv continuous` and `asv compare` are more designed for this.

**Comment by asmeurer** [comment]
Thanks I'll take a look at those two.

**Comment by asmeurer** [comment]
Although I think I maybe do want more than two commits, in case I have multiple changes in my branch. 

Maybe I should run asv against master^30..mybranch or something like that, so it can get reasonable statistics.
