### ISSUE TITLE
Results filename too long

### ISSUE THREAD

**Issue by davidruffner** [airspeed-velocity/asv#621]
I am using asv with our package that has many dependencies not all available from PyPi. So I have added them to the matrix of dependencies in `asv.conf.json`. This causes `IOError: [Errno 36] File name too long` because it includes all of the dependencies in the filename.

For example we get the following traceback after running `asv run`:
```bash
Traceback (most recent call last):
  File "/home/user/anaconda2/bin/asv", line 11, in <module>
    load_entry_point('asv', 'console_scripts', 'asv')()
  File "/home/user/Programs/pkgs/asv/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/user/Programs/pkgs/asv/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/user/Programs/pkgs/asv/asv/commands/run.py", line 132, in run_from_conf_args
    **kwargs
  File "/home/user/Programs/pkgs/asv/asv/commands/run.py", line 314, in run
    result.update_save(conf.results_dir)
  File "/home/user/Programs/pkgs/asv/asv/results.py", line 486, in update_save
    self.save(result_dir)
  File "/home/user/Programs/pkgs/asv/asv/results.py", line 469, in save
    util.write_json(path, data, self.api_version)
  File "/home/user/Programs/pkgs/asv/asv/util.py", line 629, in write_json
    with long_path_open(path, 'w') as fd:
IOError: [Errno 36] File name too long:
```

Could this be resolved by hashing the environment name?

**Comment by pv** [comment]
Yes, the names of the files don't really matter, apart from needing to
be unique for given commit+environment pair.

The parts of code that create Results objects could use
Environment.hashname instead of Environment.name. Or, pass both to
Results so that it can decide which to use if the environment name is
long.

**Comment by davidruffner** [comment]
Thanks for the quick response! Ok that is good to know that the important thing is that the names of the file be unique. I think you are right that both Environment.hashname and Environment.name could be passed so that Results could use the hashname if the regular name is too long. It's nice to have the results filenames to be human readable when possible.

This is not urgent for us, since we actually were able to shorten the name by moving some of the dependencies into our setup.py.
