### ISSUE TITLE
ASV fails to install "all" files when creating an environment

### ISSUE THREAD

**Issue by hameerabbasi** [airspeed-velocity/asv#627]
I just ran into this at [pydata/sparse](https://github.com/pydata/sparse). Output of `asv run` is at the end of this post:

Debugging steps so far:

- Created a new environment with `conda create -n temp`
- Activated it with `conda activate temp`
- Did `pip install .` in project dir (works fine)
- Dropped a shell and did `import sparse` (works fine)

Then:

- Went into listed directory: `/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/sparse`
- Saw that half the files from the project were missing (for some reason), specifically all subdirectories.

```bash
$ asv run
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6
·· Building for conda-py3.6
·· Installing into conda-py3.6.
·· Error running /Users/hameerabbasi/PycharmProjects/sparse/.asv/env/f329282d0d237249a049116b7f234e30/bin/python /Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py discover /Users/hameerabbasi/PycharmProjects/sparse/benchmarks /var/folders/cg/y4bm06ls789fz79tg85n754r0000gn/T/tmpyck9ocjp
             STDOUT -------->
             
             STDERR -------->
             Traceback (most recent call last):
               File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                 commands[mode](args)
               File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py", line 740, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py", line 725, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py", line 710, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py", line 699, in disc_files
                 module = import_module(package + filename)
               File "/Users/hameerabbasi/PycharmProjects/sparse/.asv/env/f329282d0d237249a049116b7f234e30/lib/python3.6/importlib/__init__.py", line 126, in import_module
                 return _bootstrap._gcd_import(name[level:], package, level)
               File "<frozen importlib._bootstrap>", line 994, in _gcd_import
               File "<frozen importlib._bootstrap>", line 971, in _find_and_load
               File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
               File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
               File "<frozen importlib._bootstrap_external>", line 678, in exec_module
               File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
               File "/Users/hameerabbasi/PycharmProjects/sparse/benchmarks/benchmark_coo.py", line 3, in <module>
                 import sparse
               File "/Users/hameerabbasi/PycharmProjects/sparse/.asv/env/f329282d0d237249a049116b7f234e30/lib/python3.6/site-packages/sparse/__init__.py", line 1, in <module>
                 from .coo import *
             ModuleNotFoundError: No module named 'sparse.coo'
Traceback (most recent call last):
  File "/Users/hameerabbasi/anaconda/envs/sparse/bin/asv", line 11, in <module>
    load_entry_point('asv==0.2.1', 'console_scripts', 'asv')()
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/commands/run.py", line 123, in run_from_conf_args
    **kwargs
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/commands/run.py", line 180, in run
    benchmarks = Benchmarks(conf, repo, environments, regex=bench)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmarks.py", line 299, in __init__
    benchmarks = self.disc_benchmarks(conf, repo, environments)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmarks.py", line 348, in disc_benchmarks
    dots=False)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/plugins/conda.py", line 150, in run
    return self.run_executable('python', args, **kwargs)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/environment.py", line 556, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/util.py", line 510, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/Users/hameerabbasi/PycharmProjects/sparse/.asv/env/f329282d0d237249a049116b7f234e30/bin/python /Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/asv/benchmark.py discover /Users/hameerabbasi/PycharmProjects/sparse/benchmarks /var/folders/cg/y4bm06ls789fz79tg85n754r0000gn/T/tmpyck9ocjp' returned non-zero exit status 1
$ cd /Users/hameerabbasi/anaconda/envs/sparse/lib/python3.6/site-packages/sparse
$ ls -la
total 88
drwxr-xr-x  10 hameerabbasi  staff   320 Mar 22 16:39 .
drwxr-xr-x  25 hameerabbasi  staff   800 Mar 22 16:39 ..
-rw-r--r--   1 hameerabbasi  staff   197 Mar 22 16:14 __init__.py
drwxr-xr-x   9 hameerabbasi  staff   288 Mar 22 16:39 __pycache__
-rw-r--r--   1 hameerabbasi  staff   509 Mar 22 16:39 _version.py
-rw-r--r--   1 hameerabbasi  staff   482 Mar 22 16:14 compatibility.py
-rw-r--r--   1 hameerabbasi  staff  9731 Mar 22 16:14 dok.py
-rw-r--r--   1 hameerabbasi  staff  8060 Mar 22 16:14 slicing.py
-rw-r--r--   1 hameerabbasi  staff  3645 Mar 22 16:14 sparse_array.py
-rw-r--r--   1 hameerabbasi  staff  5417 Mar 22 16:14 utils.py
```

**Comment by pv** [comment]
asv simply calls "setup.py build; pip wheel" to create a wheel for the
package. You can run `asv run -v` to debug further.

**Comment by hameerabbasi** [comment]
It seems you're right, `setup.py build` doesn't copy all required files, which is weird, because they are all in `MANIFEST.in`.

**Comment by pv** [comment]
MANIFEST.in iiuc controls what goes to sdist, but not what gets
installed.
