### ISSUE TITLE
KeyError on commit hash in asv publish

### ISSUE THREAD

**Issue by anntzer** [airspeed-velocity/asv#630]
I sometimes get
```
$ asv publish
[ 11.11%] · Loading machine info
[ 22.22%] · Getting params, commits, tags and branches
[ 22.22%] ·· Fetching recent changes
[ 33.33%] · Loading results
[ 44.44%] · Detecting steps
[ 55.56%] · Generating graphs.
[ 66.67%] · Generating output for SummaryGrid
[ 77.78%] · Generating output for SummaryList
[ 88.89%] · Generating output for RegressionsTraceback (most recent call last):
  File "/usr/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/usr/lib/python3.6/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/usr/lib/python3.6/site-packages/asv/commands/publish.py", line 69, in run_from_conf_args
    return cls.run(conf=conf, env_spec=args.env_spec)
  File "/usr/lib/python3.6/site-packages/asv/commands/publish.py", line 193, in run
    cls.publish(conf, repo, benchmarks, graphs, revisions)
  File "/usr/lib/python3.6/site-packages/asv/plugins/regressions.py", line 61, in publish
    cls._save_feed(conf, benchmarks, regressions, revisions, revision_to_hash)
  File "/usr/lib/python3.6/site-packages/asv/plugins/regressions.py", line 124, in _save_feed
    revision = revisions[results.commit_hash]
KeyError: 'd6d299c5774fe4109f69c3c701b38f86241beaf4'
```

I believe(?) this may be due to running asv once, squashing/rebasing away some commits, and rerunning asv, resulting in an internally inconsistent state? (although the given commit hash doesn't appear at all in the list of revisions known to git (even those not accessible from HEAD), so I don't really know what's happening).

In any case, wrapping that part of the code in a try... except KeyError "fixes" the issue, but perhaps there's a better solution?

**Comment by pv** [comment]
This has been fixed in master.

**Comment by anntzer** [comment]
thanks!
