### ISSUE TITLE
Problem with v0.3 (I): RuntimeError

### ISSUE THREAD

**Issue by prisae** [airspeed-velocity/asv#739]
I encountered 2 problems with `v0.3`. I report them separately.

The first one is a `RuntimeError: Failed to start server thread`; It run over 15% of the tests fine, and then failed. I installed `pip install asv=0.2.2`, and this way it was running fine. I run a few tests with `v0.2.2` and then returned to `v0.3.0`, which was fine again.

Now the tests where `asv v0.3.0` failed were tests where all tests of `empymod` failed, If I remember right due to an error in the `setup.py` file of these commits. But `asv v0.2.2` could handle that just fine, whereas `asv v0.3.0` breaks down.

```
$ asv/> asv run --skip-existing-commits ALL
· Fetching recent changes
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6.
·· Installing ad11bd14 into conda-py3.6
· Running 10400 total benchmarks (400 commits * 1 environments * 26 benchmarks)
[ 15.75%] · For empymod commit 3a48704d:
[ 15.75%] ·· Building for conda-py3.6.
[ 15.75%] ·· Benchmarking conda-py3.6
Traceback (most recent call last):
  File ".../anaconda3/bin/asv", line 11, in <module>
    sys.exit(main())
  File ".../anaconda3/lib/python3.6/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File ".../anaconda3/lib/python3.6/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File ".../anaconda3/lib/python3.6/site-packages/asv/commands/run.py", line 142, in run_from_conf_args
    **kwargs
  File ".../anaconda3/lib/python3.6/site-packages/asv/commands/run.py", line 406, in run
    launch_method=launch_method)
  File ".../anaconda3/lib/python3.6/site-packages/asv/runner.py", line 239, in run_benchmarks
    launch_method=launch_method)
  File ".../anaconda3/lib/python3.6/site-packages/asv/runner.py", line 379, in get_spawner
    return spawner_cls(env, benchmark_dir)
  File ".../anaconda3/lib/python3.6/site-packages/asv/runner.py", line 692, in __init__
    raise RuntimeError("Failed to start server thread")
RuntimeError: Failed to start server thread 
```

**Comment by pv** [comment]
What operating system? Linux(?) distribution?

**Comment by prisae** [comment]
Yes, Linux. I tried it on Ubuntu 16.04 and 18.04, and on the server which is RHEL 7.2. Using always Python 3.6, installed with conda. I will provide more information in a sec.

**Comment by prisae** [comment]
I think the error is related to the case when a module is not installed (say, for instance, `numexpr`).

Here a specific example. The following works, using `asv v0.2.2`:
```
~/> pip install asv==0.2.2
Collecting asv==0.2.2
Requirement already satisfied: six>=1.4 in /home/dtr/anaconda3/lib/python3.6/site-packages (from asv==0.2.2) (1.11.0)
Installing collected packages: asv
  Found existing installation: asv 0.3
    Uninstalling asv-0.3:
      Successfully uninstalled asv-0.3
Successfully installed asv-0.2.2
~/> git clone git@github.com:empymod/asv.git
Cloning into 'asv'...
remote: Counting objects: 663, done.
remote: Total 663 (delta 0), reused 0 (delta 0), pack-reused 663
Receiving objects: 100% (663/663), 1.46 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% (506/506), done.
Checking connectivity... done.
~/> cd asv/
asv/> asv run 6f285823
· Cloning project.
· Fetching recent changes
· Creating environments...
· Discovering benchmarks
·· Uninstalling from conda-py3.6
·· Building for conda-py3.6
·· Installing into conda-py3.6...
· Running 1976 total benchmarks (76 commits * 1 environments * 26 benchmarks)
[  0.00%] · For empymod commit hash 6f285823:
[  0.00%] ·· Building for conda-py3.6.
[  0.00%] ·· Benchmarking conda-py3.6
[  0.00%] ··· Setting up /home/dtr/asv/benchmarks/kernel.py:33
[  0.05%] ··· Running model.Analytical.time_analytical                             failed
[  0.10%] ··· Running model.Bipole.time_bipole_freq                                failed
[  0.15%] ··· Running model.Bipole.time_bipole_time                                failed
[  0.20%] ··· Running model.Dipole.time_dipole_freq                                failed
[  0.25%] ··· Running model.Dipole.time_dipole_time                                failed
[  0.30%] ··· Running model.Various.time_dipole_difflsrclrec_42                    failed
[  0.35%] ··· Running model.Various.time_dipole_highfreq_11                        failed
[  0.40%] ··· Running model.Various.time_dipole_land_angle_16                      failed
[  0.46%] ··· Running model.Various.time_dipole_marine_angle_12                    failed
[  0.51%] ··· Running transform.Hankel.time_fht_lagged                             failed
[  0.56%] ··· Running transform.Hankel.time_fht_splined                            failed
[  0.61%] ··· Running transform.Hankel.time_fht_standard                           failed
[  0.66%] ··· Running transform.Hankel.time_hquad                                  failed
[  0.71%] ··· Running transform.Hankel.time_hqwe_splined                           failed
[  0.76%] ··· Running transform.Hankel.time_hqwe_standard                          failed
``` 
So all of the tests fail, but `asv` itself doesn't fail, it happily continues with the next commit.

The same doesn't work for `asv v0.3.0`:
```
~/> pip install asv==0.3
Collecting asv==0.3
Requirement already satisfied: six>=1.4 in /home/dtr/anaconda3/lib/python3.6/site-packages (from asv==0.3) (1.11.0)
Installing collected packages: asv
  Found existing installation: asv 0.2.2
    Uninstalling asv-0.2.2:
      Successfully uninstalled asv-0.2.2
Successfully installed asv-0.3
~/> git clone git@github.com:empymod/asv.git 
Cloning into 'asv'...
remote: Counting objects: 663, done.
remote: Total 663 (delta 0), reused 0 (delta 0), pack-reused 663
Receiving objects: 100% (663/663), 1.46 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% (506/506), done.
Checking connectivity... done.
~/> cd asv
asv/> asv run 6f285823
· Cloning project.
· Fetching recent changes
· Creating environments....
· Discovering benchmarks
·· Uninstalling from conda-py3.6.
·· Building 6f285823 for conda-py3.6
·· Installing 6f285823 into conda-py3.6.
·· Error running /home/dtr/asv/env/f329282d0d237249a049116b7f234e30/bin/python /home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py discover /home/dtr/asv/benchmarks /tmp/tmp6snony0a/result.json
   STDOUT -------->
   
   STDERR -------->
   Traceback (most recent call last):
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 1133, in <module>
       main()
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 1126, in main
       commands[mode](args)
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 855, in main_discover
       list_benchmarks(benchmark_dir, fp)
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 840, in list_benchmarks
       for benchmark in disc_benchmarks(root):
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 738, in disc_benchmarks
       for module in disc_modules(root_name):
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 720, in disc_modules
       for item in disc_modules(name):
     File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py", line 715, in disc_modules
       module = import_module(module_name)
     File "/home/dtr/asv/env/f329282d0d237249a049116b7f234e30/lib/python3.6/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
     File "<frozen importlib._bootstrap>", line 994, in _gcd_import
     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
     File "/home/dtr/asv/benchmarks/kernel.py", line 1, in <module>
       import numpy as np
   ModuleNotFoundError: No module named 'numpy'

Traceback (most recent call last):
  File "/home/dtr/anaconda3/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/commands/run.py", line 142, in run_from_conf_args
    **kwargs
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/commands/run.py", line 222, in run
    commit_hashes, regex=bench)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmarks.py", line 136, in discover
    benchmarks = cls._disc_benchmarks(conf, repo, environments, commit_hash)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmarks.py", line 190, in _disc_benchmarks
    dots=False)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/plugins/conda.py", line 184, in run
    return self.run_executable('python', args, **kwargs)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/plugins/conda.py", line 190, in run_executable
    return super(Conda, self).run_executable(executable, args, **kwargs)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/environment.py", line 766, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/home/dtr/anaconda3/lib/python3.6/site-packages/asv/util.py", line 642, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/dtr/asv/env/f329282d0d237249a049116b7f234e30/bin/python /home/dtr/anaconda3/lib/python3.6/site-packages/asv/benchmark.py discover /home/dtr/asv/benchmarks /tmp/tmp6snony0a/result.json' returned non-zero exit status 1
```

**Comment by prisae** [comment]
Doing for `asv v0.3.0`
```
./env/f329282d0d237249a049116b7f234e30/bin/pip install scipy numexpr
```
resolves the issue, afterwards it runs fine. So there is an issue with the `setup.py` file in `empymod` or similar, it is a bad commit, my bad. However, `asv v0.2.2` (and earlier) happily run through them, whereas `asv v0.3.0` is failing.

**Comment by pv** [comment]
Reproduced, there's a bug in 0.3 when benchmark suite fails to import -- it should catch that.
Workaround: --launch-method=spawn

**Comment by pv** [comment]
#742, #743

**Comment by prisae** [comment]
Great, thanks @pv!
