### ISSUE TITLE
running profile without commit results in obscure  AttributeError: 'Results' object has no attribute 'env'

### ISSUE THREAD

**Issue by yarikoptic** [airspeed-velocity/asv#801]
```shell
$> asv profile  api.testds.time_create_test_dataset2x2      
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/asv", line 11, in <module>
    load_entry_point('asv', 'console_scripts', 'asv')()
  File "/home/yoh/proj/misc/asv/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/yoh/proj/misc/asv/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/yoh/proj/misc/asv/asv/commands/profiling.py", line 94, in run_from_conf_args
    **kwargs)
  File "/home/yoh/proj/misc/asv/asv/commands/profiling.py", line 148, in run
    for env in environments)
  File "/home/yoh/proj/misc/asv/asv/commands/profiling.py", line 148, in <genexpr>
    for env in environments)
AttributeError: 'Results' object has no attribute 'env'
```
and runs ok if I give HEAD
```shell
$> asv profile api.testds.time_create_test_dataset2x2 HEAD
· Discovering benchmarks
·· Uninstalling from virtualenv-py2.7.
·· Building ed8136f8 <bm-monkey-patch-is-interactive> for virtualenv-py2.7.
·· Installing ed8136f8 <bm-monkey-patch-is-interactive> into virtualenv-py2.7.
· Profile data does not already exist. Running profiler now.
·· Benchmarking virtualenv-py2.7
··· Running (api.testds.time_create_test_dataset2x2--).
··· api.testds.time_create_test_dataset2x2         
...
```

```shell
$> asv --version
asv 0.4.dev1608+7afea8e5
```

**Comment by jbrockmendel** [comment]
I'm getting the same error, but specifying HEAD doesn't help

**Comment by HaoZeke** [comment]
Can't reproduce this on `master`.

**Comment by brandonwillard** [comment]
I'm seeing this issue with `asv` at 0.6.3 and `asv_runner` 0.2.1.  

Looking at the `asv.results.Results` class and I don't see where `Results` gets a `.env` field, nor do I see it referenced or used anywhere in `asv` aside from the `asv.profiling.Profile.run` (i.e. where the error occurs).

Changing `result.env.name` to `result.env_name` works until `result.env.checkout_project` is needed.
