### ISSUE TITLE
Memory benchmark error

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#889]
For the astropy benchmarks, we are running into an error with the memory benchmarks:

```
[ 19.84%] ··· io_ascii.table.TableSuite.mem_table_outputter               failed

[ 19.84%] ···· Traceback (most recent call last):

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 1184, in main_run_server

                   main_run(run_args)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 1058, in main_run

                   result = benchmark.do_run()

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 537, in do_run

                   return self.run(*self._current_params)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 729, in run

                   sizeof2 = asizeof.asizeof([obj, obj])

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2708, in asizeof

                   s = _asizer.asizeof(*t)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2137, in asizeof

                   return sum(self._sizer(o, 0, 0, None) for o in objs)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>

                   return sum(self._sizer(o, 0, 0, None) for o in objs)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2075, in _sizer

                   s += z(o, i, d, None)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2075, in _sizer

                   s += z(o, i, d, None)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2075, in _sizer

                   s += z(o, i, d, None)

                 [Previous line repeated 1 more time]

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 2050, in _sizer

                   infer=self._infer_)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 1711, in _typedef

                   v.set(**_numpy_kwds(obj))

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 1269, in set

                   self.reset(**d)

                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/extern/asizeof.py", line 1278, in reset

                   raise ValueError('invalid option: %s=%r' % ('base', base))

               ValueError: invalid option: base=-7880
```

Before I dig deeper into this, I just wanted to check whether this is a known issue? The benchmarks are at https://github.com/astropy/astropy-benchmarks

**Comment by pllim** [comment]
xref astropy/astropy-benchmarks#87 

Out of curiousity, I tried to search The Internet for this error but did not get an answer. I also tried running the code being profiled locally and did not see significant memory usage (so the machine running out of memory for this particular call is unlikely).

**Comment by pv** [comment]
That's some bug in the bundled `asizeof.py` for the specific object in question, i.e. comes from `asv.extern.asizeof.asizeof(your_object)` failing.

**Comment by pllim** [comment]
Hmm. I cannot reproduce the failure locally with Python 3.7, `asizeof` from `asv 0.5.dev1839+cc460ced`, and `astropy 4.1.dev26986`.

```python
>>> from astropy.io.ascii import core
>>> from asv.extern.asizeof import asizeof
>>> cols = [core.Column(str(i + 1)) for i in range(3)]
>>> outputter = core.TableOutputter()
>>> my_obj = outputter(cols, {'table': {}})
>>> asizeof(my_obj)
2168
```

**Comment by pv** [comment]
This however fails (run in `astropy-benchmarks` directory):
```
from benchmarks.io_ascii.table import TableSuite
from asv.extern import asizeof
f = TableSuite()
f.setup()
obj = f.mem_table_outputter()
asizeof.asizeof(obj)
```

**Comment by pllim** [comment]
Oh, ops... I didn't see this part of the setup. I can reproduce it now. Good catch!

```python
import random
from string import ascii_uppercase as uppercase

lst = []
lst.append([random.randint(-500, 500) for i in range(1000)])
lst.append([random.random() * 500 - 500 for i in range(1000)])
lst.append([''.join([random.choice(uppercase) for j in range(6)]) for i in range(1000)])

for col, x in izip(cols, lst):
    col.data = x
```

**Comment by pllim** [comment]
So, it works on empty `Table` but not on `Table` with data (not masked, by the way). I did find a workaround but not sure if that is equivalent.

```python
>>> a = obj.as_array()                                                                         
>>> asizeof.asizeof(a)                                                                         
40096
```

**Comment by pv** [comment]
I guess the main point here would be to find a fix for `asizeof`, but
it's bundled from some other project, and I've so far never actually
read its code.

**Comment by pllim** [comment]
I tried to find the original source of `asizeof` but the most I can find are tarballs on SourceForge and then I lost interest. 😬  It does seem the bundled version is recent enough though.
