### ISSUE TITLE
asv dev returns zero exit code even if an error occurred

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#890]
See below - the exit code of ``asv dev`` is 0 even though a failure happened:

```
(dev) tom@torren:~/Code/astropy-benchmarks$ asv dev --bench _out
· Discovering benchmarks
· Running 8 total benchmarks (1 commits * 1 environments * 8 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_tom_python_dev_bin_python3.7
[  6.25%] ··· io_ascii.table.TableSuite.mem_table_outputter                                                                                                                                          failed
[  6.25%] ···· Traceback (most recent call last):
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 729, in run
                   sizeof2 = asizeof.asizeof([obj, obj])
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2708, in asizeof
                   s = _asizer.asizeof(*t)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in asizeof
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 [Previous line repeated 1 more time]
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2050, in _sizer
                   infer=self._infer_)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1711, in _typedef
                   v.set(**_numpy_kwds(obj))
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1269, in set
                   self.reset(**d)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1278, in reset
                   raise ValueError('invalid option: %s=%r' % ('base', base))
               ValueError: invalid option: base=-7880

[ 12.50%] ··· io_ascii.table.TableSuite.time_table_outputter                                                                                                                                       5.12±0ms
[ 18.75%] ··· table.TimeMaskedTable.time_join_outer                                                                                                                                                2.63±0ms
[ 25.00%] ··· table.TimeTable.time_join_outer                                                                                                                                                      1.63±0ms
[ 31.25%] ··· units.TimeQuantityOpLargeArray.time_quantity_np_sqrt_out                                                                                                                             1.33±0ms
[ 37.50%] ··· units.TimeQuantityOpLargeArray.time_quantity_np_square_out                                                                                                                           13.4±0ms
[ 43.75%] ··· units.TimeQuantityOpSmallArray.time_quantity_np_sqrt_out                                                                                                                              146±0μs
[ 50.00%] ··· units.TimeQuantityOpSmallArray.time_quantity_np_square_out                                                                                                                            284±0μs
(dev) tom@torren:~/Code/astropy-benchmarks$ echo $?
0
```

**Comment by pv** [comment]
Intended behavior. `asv dev --strict` as alternative.

**Comment by astrofrog** [comment]
Ah thanks!
