### ISSUE TITLE
asv.conf.json The file is at the same level as benchmarks. In the configuration file, the configuration file is configured with "repo": ".". Why do you report an error: windowserror: [error 267] the directory name is invalid

### ISSUE THREAD

**Issue by WilliamHeaven** [airspeed-velocity/asv#941]
Directory hierarchy and configuration:
![image](https://user-images.githubusercontent.com/28834227/87238354-1fdad500-c434-11ea-8cb0-180c7f319adb.png)

Error：
```
   '4GB'.
Traceback (most recent call last):
ram []: � No executable found for python 3.6
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\bin\asv-script.py", line 11, in <module>
    load_entry_point('asv==0.4.2', 'console_scripts', 'asv')()
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\main.py", line 38, in main
    result = args.func(args)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\commands\__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\commands\run.py", line 152, in run_from_conf_args
    **kwargs
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\commands\run.py", line 195, in run
    commit_hashes = list(set([repo.get_hash_from_name(branch) for branch in conf.branches]))
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\plugins\git.py", line 137, in get_hash_from_name
    dots=False).strip().split()[0]
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\plugins\git.py", line 73, in _run_git
    return util.check_output([self._git] + args, env=env, **kwargs)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\asv\util.py", line 511, in check_output
    proc = subprocess.Popen(args, **kwargs)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\lib-python\2.7\subprocess.py", line 405, in __init__
    errread, errwrite)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\lib-python\2.7\subprocess.py", line 669, in _execute_child
    startupinfo)
  File "C:\hostedtoolcache\windows\PyPy\2.7.13\x86\site-packages\virtualenv\util\subprocess\_win_subprocess.py", line 122, in CreateProcess
    raise WinError()
WindowsError: [Error 267] The directory name is invalid
##[error]Process completed with exit code 1.
```

**Comment by HaoZeke** [comment]
This can be closed. The problem here is that the PyPy version used is 2.7, and `asv` is looking for Python 3.6
