### ISSUE TITLE
setup() not being run before benchmark runs

### ISSUE THREAD

**Issue by asmeurer** [airspeed-velocity/asv#966]
```py
$ cat benchmarks/test.py
class TimeBenchmarkTest:
    def setup(self):
        self.x = []

    def time_1(self):
        assert len(self.x) == 0
        self.x.append(0)

    def time_2(self):
        assert len(self.x) == 0
```

```
$ asv run -n -b TimeBenchmarkTest -s 1 -e
...
[ 25.00%] ··· Running (test.TimeBenchmarkTest.time_1--)..
[ 75.00%] ··· test.TimeBenchmarkTest.time_1                                                                                                                        failed
[ 75.00%] ···· Traceback (most recent call last):
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 1315, in <module>
                   main()
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 1308, in main
                   commands[mode](args)
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 627, in run
                   samples, number = self.benchmark_timing(timer, min_repeat, max_repeat,
                 File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.8/site-packages/asv/benchmark.py", line 663, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/Users/aaronmeurer/Documents/versioned-hdf5/.asv/env/5bcab3442271e1ed0cd0c2ca3bebbfe2/lib/python3.8/timeit.py", line 177, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/Users/aaronmeurer/Documents/versioned-hdf5/benchmarks/test.py", line 6, in time_1
                   assert len(self.x) == 0
               AssertionError

[100.00%] ··· test.TimeBenchmarkTest.time_2
```

Adding a teardown, like

```py
    def teardown(self):
        self.x.clear()
```

does not fix it.

**Comment by pv** [comment]
https://asv.readthedocs.io/en/stable/benchmarks.html#timing-benchmarks see `number`.

**Comment by asmeurer** [comment]
This directly contradicts what is written at https://asv.readthedocs.io/en/stable/writing_benchmarks.html?highlight=setup#setup-and-teardown-functions

> The setup method is run multiple times, for each benchmark and for each repeat.

Anyway, what's the point of this? For my benchmarks, it is impossible to run the benchmark multiple times with the same setup, so I am forced to include the setup in the benchmark time.

**Comment by asmeurer** [comment]
Also the existence (and documentation) of `setup_cache` implies that this is a workaround if calling setup() each time is too expensive.

**Comment by flying-sheep** [comment]
I can’t figure out how to actually use `number`. I tried setting it as an attribute on the module and on a function, but neither results in `setup` being run reliably:

I added an `assert`ion checking if the setup ran, and it fails. Tracebacks show that setup is run, then the benchmark twice, and then teardown (I assume because the `assert` fails and the `finally` block is triggered)

How do I force asv to work as documented?

**Comment by crusaderky** [comment]
This issue fundamentally prevents any and all benchmark suites where

a. any tests in the suite have random variance, and
b. any tests in the suite (not necessarily the same as above) modify the setup state.

Is there a reason why it is not treated as high priority?

**Comment by kraktus** [comment]
Bumping this as well, it is very frontally against the documentation in "writing benchmarks".

> Note that although different benchmarks run in separate processes, for a given benchmark repeated measurement (cf. repeat attribute) and profiling occur within the same process. For these cases, the setup and teardown routines are run multiple times in the same process.

Although this can be mitigated by setting `number` to 1, it should IMO be the default and the documentation which more clear about it: https://asv.readthedocs.io/en/stable/benchmarks.html#timing-benchmarks

**Comment by HaoZeke** [comment]
Root cause: `timeit(number=N)` runs setup once then the statement N times, and the warmup loop suppressed re-setup entirely; `redo_setup` only ran between samples. That warmup suppression is also why explicit `number=1` still failed as reported above.

Runner fix: airspeed-velocity/asv_runner#53 -- with setup hooks present every timed call now observes freshly set-up state: warmup re-runs setup between calls, auto-calibrated `number` resolves to 1, and an explicit `number>1` batches with setup interleaved between individually timed calls (only the calls are timed). Benchmarks without `setup`, and `setup_cache` users, keep plain `timeit` batching.

Docs: #1608
