### ISSUE TITLE
Unable to update existing gh-pages branch

### ISSUE THREAD

**Issue by nicholaiTukanov** [airspeed-velocity/asv#977]
My situation is that I have 2 machines that I want to compare benchmarks on.

I have gathered the benchmark results on first machine and used `asv gh-pages` to create and push to a new `gh-pages` branch, but when I want to do the same on the second machine, `asv gh-pages` errors out with the following:

```
[100.00%] · Error running /usr/bin/git fetch /home/nicholai/numpy/benchmarks/html gh-pages:gh-pages (exit status 1)
            STDOUT -------->
            
            STDERR -------->
            warning: no common commits
            From /home/nicholai/numpy/benchmarks/html
             ! [rejected]            gh-pages   -> gh-pages  (non-fast-forward)

Traceback (most recent call last):
  File "/home/nicholai/miniconda3/envs/simple/bin/asv", line 8, in <module>
    sys.exit(main())
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/plugins/github.py", line 40, in run_from_conf_args
    return cls.run(conf=conf, no_push=args.no_push, rewrite=args.rewrite)
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/plugins/github.py", line 86, in run
    util.check_call([git, 'fetch', os.path.abspath(conf.html_dir),
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/util.py", line 366, in check_call
    check_output(
  File "/home/nicholai/miniconda3/envs/simple/lib/python3.9/site-packages/asv/util.py", line 685, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git fetch /home/nicholai/numpy/benchmarks/html gh-pages:gh-pages' returned non-zero exit status 1
````

According to the documentation, shouldn't `asv gh-pages` see that there already exists a `gh-pages` branch, and then update it accordingly with the new results? 

How can I get it to push the new machine's results so that I can view it correctly?

Also, it seems like some has had similar problems before in #951 and #515

**Comment by mattip** [comment]
I think this is different from #515 which was solved by providing the `--rewrite` option. It seems what is needed here is a `git fetch` before the benchmark run?
